# Generated by Django 4.1.6 on 2023-02-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pereval_added",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("row_data", models.JSONField()),
                ("images", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENGING", "pending"),
                            ("ACCEPTED", "accepted"),
                            ("REJECTED", "rejected"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
